apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-auth-sa
  namespace: analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-auth-role
  namespace: analytics
rules:
- apiGroups: [""]
  resources: ["services", "pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-auth-rolebinding
  namespace: analytics
subjects:
- kind: ServiceAccount
  name: user-auth-sa
  namespace: analytics
roleRef:
  kind: Role
  name: user-auth-role
  apiGroup: rbac.authorization.k8s.io
